### ISSUE TITLE
I need DIVE tokens.

### ISSUE THREAD

**Issue by Omudia** [OwshenNetwork/owshen#103]
My wallet was on the list of eligible wallets to receive test tokens, but there's no token in my wallet. 

I need some test tokens to be able to carry out some testnet transactions.

Here's my address OoOo3286390166fefaea164de66d773f08b3a6fde69526f4d570edc8c41b5f8823b23

**Comment by zico419** [comment]
Same with me 

OoOo32a3f5f54033aa51f1add55f4aad3b31a04fcaabd6005d279a4e45a6d851a41d8
