### ISSUE TITLE
BUG: `--ip` and `--port` don't affect sone function in wallet webpage 

### ISSUE THREAD

**Issue by Halimao** [OwshenNetwork/owshen#110]
I ran the wallet on a server with `--ip 0.0.0.0 --port 8080`, but it still calls `http://localhost:9000/set-network?chain_id=11155111`

![image](https://github.com/OwshenNetwork/owshen/assets/25278203/55c5fd9c-7c49-48a3-8dcb-673471f6d7cc)

**Comment by OwshenNetwork** [comment]
Tnx, fixed.

Will publish the fix in the next release

**Comment by Halimao** [comment]
@OwshenNetwork Hi sir, when will you publish the next release?
