### ISSUE TITLE
[Badge - Cryptobike]

### ISSUE THREAD

**Issue by cryptobike07** [OwshenNetwork/owshen#13]
Hi Owshen Team! I'm claiming my contributor badge for completing a developer tutorial. 😀

Github Username: cryptobike07
Tutorial Repo: https://github.com/cryptobike07/genesis
Requested badge: Tutorial
Discord: cryptobike07

**Comment by likemike007** [comment]
Hi Owshen Team! I'm claiming my contributor badge for completing a developer tutorial. 😀

Github Username: likemike007
Tutorial Repo:https://github.com/likemike007/sukuna7/blob/main/README.md
Requested badge: Tutorial
Discord: mykelalmoro
