### ISSUE TITLE
Badge - JomaBautista

### ISSUE THREAD

**Issue by JomaBautista** [OwshenNetwork/owshen#36]
Hi Owshen Team,

Submitting my contribution for my contributor badge for completing a developer tutorial.

Github Username: JomaBautista
Tutorial Repo: https://github.com/JomaBautista/Owshen.git
Requested badge: Tutorial
Discord: jmib007

Thank you

**Comment by cmnkobo** [comment]
Hi Owshen Team,

Submitting my contribution for my contributor badge for completing a developer tutorial.

Github Username: cmnkobo
Tutorial Repo: https://github.com/cmnkobo/genesis.git
Requested badge: Tutorial
Discord: chrismike1

Thank you
