### ISSUE TITLE
[Badge - Jonikum]

### ISSUE THREAD

**Issue by Jonikum** [OwshenNetwork/owshen#5]
Hi Owshen team! I'm claiming my contributor badge for completing a developer tutorial. 😀

Github Username: Jonikum
Tutorial Repo: https://mirror.xyz/0x6180Af5335E492Bb91D2613035D75c33BFc879c2/OkI7vYnWdfgidXkZFeVOhPPtcl4cd5mzRK44JKu2FEU
Requested badge: Tutorial

**Comment by OwshenNetwork** [comment]
@Jonikum Can't find you on our Discord server. What's your username? :)

**Comment by Jonikum** [comment]
.joniwow my discord username sir
