### ISSUE TITLE
badge ronindboss

### ISSUE THREAD

**Issue by Ronindboss** [OwshenNetwork/owshen#78]
Hi Owshen Team! I'm claiming my contributor badge for completing a developer tutorial. 😀

Github Username: ronindboss
Tutorial Repo: https://medium.com/@ninaclaire07/owshen-aidrop-guide-63b22ccf9fc4
Requested badge: Tutorial
Discord: roningrahix

**Comment by jeyban** [comment]
Wazzup Owshen Team:) I am claiming my contributor role badge for completing a developer tutorial

Github Username: jeyban
Tutorial Repository: https://github.com/jeyban/OwshenNetwork-Mobile-Guide.git
Requested Badge: Tutorial
Discord: @aljeansuiswap
