### ISSUE TITLE
No Dive tokens on my wallet address

### ISSUE THREAD

**Issue by RestlessHavoc** [OwshenNetwork/owshen#83]
I have completed the process for viewing the app image of my wallet but i'm seeing no Dive tokens there. I did the bermuda airdrop task and was on the Github list the team posted. My wallet address is:
OoOo21123000cb0118c4127ea73c19acd6df28f4452cd8551523abe2a5b3fad2d5820

**Comment by Lodia001** [comment]
This is a screenshot of my wallet
![Screenshot 2024-01-21 031932](https://github.com/OwshenNetwork/owshen/assets/101640538/2a794176-6d71-4c5b-b7b3-e437dbb4abda)

**Comment by linhpq0610** [comment]
<img width="443" alt="Screenshot 2024-01-21 172424" src="https://github.com/OwshenNetwork/owshen/assets/143584755/82078d78-1f11-4c39-bda9-2b8fe5ba0111">

**Comment by Lodia001** [comment]
Oh......my bad....guess I didn't read between the lines

**Comment by linhpq0610** [comment]
sorry, I told you wrong above, you can solve the problem by reloading the page or run command in step 6 again

**Comment by ajalaoluwasogo** [comment]
OoOo31b26a474776a477a900359d5a1429aed3cfafc717c02e6a4f33e8b2697db2dab
