### ISSUE TITLE
GITPOD USER, FUSE UPDATE BEFORE RUNNING OWSHEN

### ISSUE THREAD

**Issue by philip0529** [OwshenNetwork/owshen#88]
## UPDATE

FOLLOW THEIR LATEST INSTRUCTION:
https://github.com/OwshenNetwork/genesis

Prepare at least .2 Sepolia ETH with your imported SP (Owshen) for Sepolia gas fee.

## I am not a veteran but here's my flow to run in GITPOD.

sudo apt update
sudo apt install libfuse2

sudo apt install fuse libfuse2 nodejs -y
sudo npm install -g snarkjs

wget https://github.com/OwshenNetwork/owshen/releases/download/v0.1.2/Owshen_v0.1.2_x86_64.AppImage

chmod +x Owshen_v0.1.2_x86_64.AppImage

./Owshen_v0.1.2_x86_64.AppImage init --mnemonic "[YOUR 12 WORD MNEMONIC-PHRASE]"

./Owshen_v0.1.2_x86_64.AppImage wallet

## OR
sudo apt update
sudo apt install libfuse2

sudo apt install fuse libfuse2
sudo modprobe fuse
sudo groupadd fuse

user="$(whoami)"
sudo usermod -a -G fuse $user

sudo apt install fuse libfuse2 nodejs -y
sudo npm install -g snarkjs

wget https://github.com/OwshenNetwork/owshen/releases/download/v0.1.2/Owshen_v0.1.2_x86_64.AppImage

chmod +x Owshen_v0.1.2_x86_64.AppImage

./Owshen_v0.1.2_x86_64.AppImage init --mnemonic "[YOUR 12 WORD MNEMONIC-PHRASE]"

./Owshen_v0.1.2_x86_64.AppImage wallet

### thread 'tokio-runtime-worker' panicked at 'called Result::unwrap() on an Err value: MiddlewareError { e: JsonRpcClientError(JsonRpcError(JsonRpcError { code: -32000, message: "max message response size exceed. upgrade your plan at https://blockpi.io/", data: None })) }', src/apis/coins.rs:103:22

# I AM NOT A VETERAN, PLEASE CORRECT ME IF YOU THINK WHAT'S BEST.

**Comment by xcvmvc** [comment]
this show balance token ?

**Comment by philip0529** [comment]
> this show balance token ?

Yes, it shows balance. You just have to wait the update/loading once you open the prompted link and connected your metamask (imported your SP).

**Comment by oliveskin** [comment]
The error you see, @philip0529 This is due to RPC / rate limit. your gitpod should still be fine (check under usage limits). 
I reckon tomorrow the team may upgrade the blockpi service or find a workaround.

**Comment by philip0529** [comment]
> The error you see, @philip0529 This is due to RPC / rate limit. your gitpod should still be fine (check under usage limits). I reckon tomorrow the team may upgrade the blockpi service or find a workaround.

Ohh, nice, thanks for updating!

**Comment by Lasgidi1969** [comment]
I'm seeing a different kind of error at my ends I don't even understand 
I have refreshed,
Created new workspace more than 10 times still the same thing
I have cleared my cache and history still the same thing

![IMG-20240122-WA0006](https://github.com/OwshenNetwork/owshen/assets/119519396/3b26cc6a-d613-428b-9cba-c4ca017920bf)
