### ISSUE TITLE
Wallet on Waitlist showing 0 DIVE 

### ISSUE THREAD

**Issue by Symonpeetta** [OwshenNetwork/owshen#89]
![Screenshot_20240121-172127](https://github.com/OwshenNetwork/owshen/assets/65063958/74d4d495-eb02-4190-8052-fc2f3e362310)

**Comment by Neotravolta** [comment]
Same issues here as well even after running the programs on gitpod and Ubuntu, all the same 
![IMG-20240121-WA0033](https://github.com/OwshenNetwork/owshen/assets/142179013/d3f6bccf-6a1f-4988-ae64-10d2c0db8d35)
And my wallet is whitelisted

**Comment by tickideas** [comment]
I haven't received any DIVE yet if though I was whitelisted.
OoOo30f1e7f5fda39ffc3dd5b3d83268c923e6bc0d145094e50e51c67aba6819f2b76

**Comment by didiansyah** [comment]
Still have issue 0 DIVE
OoOo322e812a86f3043408ec275b992d6317ef44170d9b31f18192a9c8627d288e65d

**Comment by Barliyer** [comment]
same here OoOo3088b3af10d7a315760f3230a645d45025773b4e5c37ced9a2f22eb9506be9cca

**Comment by Festus74608** [comment]
I was eligible and didn't receive any $DIVE
OoOo31ab2bf4b7726a14820f9da011652db1d78f708c405298018799884ba1cc3ae85

**Comment by Oluwatunmise116** [comment]
same here OoOo22df5f4dcb7e26b82c35d306e9c436268271f26fee1fc67b6a3f5accce3670235
