### ISSUE TITLE
Wallet on Waitlist showing 0 DIVE

### ISSUE THREAD

**Issue by tickideas** [OwshenNetwork/owshen#94]
My wallet is showing 0 DIVE in tho i made the airdrop whitelist.
Owshen Address: OoOo30f1e7f5fda39ffc3dd5b3d83268c923e6bc0d145094e50e51c67aba6819f2b76

![image_2024-01-21_164336246](https://github.com/OwshenNetwork/owshen/assets/103061858/2b74d14a-57d7-4ee9-8657-d8f590710081)

**Comment by maryprunes28** [comment]
same issue for me OoOo201995fc55d1546dc98748ed71a799e3170b44588cc6550908fd9d0749eb200b2
