### ISSUE TITLE
wallet on waitlist showing 0 DIVE

### ISSUE THREAD

**Issue by bayyesterday** [OwshenNetwork/owshen#95]
OoOo21079f982acd794ada277f78b31b08e28e1fec88a0cfd3c0c83b5f28907c8807b

**Comment by Ifenio** [comment]
OoOo22d01a195b87d9012b2f67afec284926b6a8d3e56d63bed5db07d34b4d0dd6d82

**Comment by Barliyer** [comment]
OoOo3088b3af10d7a315760f3230a645d45025773b4e5c37ced9a2f22eb9506be9cca

**Comment by maryprunes28** [comment]
OoOo201995fc55d1546dc98748ed71a799e3170b44588cc6550908fd9d0749eb200b2

**Comment by ajalaoluwasogo** [comment]
OoOo31b26a474776a477a900359d5a1429aed3cfafc717c02e6a4f33e8b2697db2dab

**Comment by kumam27** [comment]
OoOo319baa0ed9466a67b83b71ef6cce190b1b813b6807daa0fd794be07cc848e6a36

**Comment by Napoleon-Jahmiu** [comment]
OoOo30f794db35ff3b37ea3408607d3519509ae96c3ee5aaec268ded005af0bb92e87

**Comment by sagara02** [comment]
OoOo2106d9caf72cb4de3f38cad91a0c38f31ee516db64fed5d6c133e5c4f575b104b

**Comment by Bamiboygraphics** [comment]
OoOo2061e031e2a5acf6184f9dcd98dff9659da69abf9203cbfd1a42614f8d529b24d

**Comment by Fahd202** [comment]
0o0o21f322998e941f58dedfbb2ce2356ad0b5beefba0af1e1f1e4c1abf83a269505

**Comment by denisofyan** [comment]
OoOo22c3a1846090f36991b772ffba1fd6f5e0f7a679c83c4b09bf4b54d3140140c96

**Comment by ChukwuemekaBello** [comment]
OoOo31bd02162181c8cdbc6446505630d56bd118edea47c49064a64a94f8e7cd0ccfd

**Comment by shivsantosh1996** [comment]
OoOo2165d6777dfd57ffe81b782a22557d259f58431598cef6f96fbfdd6893146bc24

**Comment by maryprunes28** [comment]
still the same issue after many days.

**Comment by Nelson-Favour** [comment]
no dive has been sent to my wallet
been loading and showing zero for hours


OoOo22753703ecbcca1e75f91f79f38f520b1ceac07f5e49b138a71b1ee338126bdf9

**Comment by Napoleon-Jahmiu** [comment]
OoOo30f794db35ff3b37ea3408607d3519509ae96c3ee5aaec268ded005af0bb92e87

**Comment by Cryptotronx** [comment]
OoOo32e3ae1057a7f75ff00b27c0cd80e400fb8ed8fa758a9a03601b20fdcfab4b851

**Comment by Kayx3e** [comment]
Please I need the $DIVE test tokens

OoOo3099014e9d2bb8fba7991702227ff8ff2bebd583074f5c16268e005a3bf3a25a3

**Comment by Napoleon-Jahmiu** [comment]
OoOo30f794db35ff3b37ea3408607d3519509ae96c3ee5aaec268ded005af0bb92e87

**Comment by Napoleon-Jahmiu** [comment]
OoOo30f794db35ff3b37ea3408607d3519509ae96c3ee5aaec268ded005af0bb92e87

**Comment by Vicmichael** [comment]
OoOo21f964f0bc7a3552eb593203ba823f75daca3dcc93277874452f2e201c5a9702b

**Comment by Kayx3e** [comment]
Good morning

Please how do I get DIVE tokens

**Comment by slimegod1** [comment]
i need the dive tokens 
OoOo21ce8bb50f12339ebbff2402988c9c7cd00c0c9b5eb3d8d3367212080ddb2919d

**Comment by udangijo** [comment]
Please send me DIVE tokens. Thanks

OoOo22f8f8092d7773f31128aa9b595d65bb20475ee443bde78a316ea185fc3a69235

**Comment by DestroBlaq** [comment]
OoOo22a85610a9d61de47c40d762dca6f4f245638b9b784d04a3287d92aa3591e2f5a

**Comment by greatestofall** [comment]
OoOo30e4a579411397935cb95367fd005654155f5bd2286bcf84fec6aab3cc083af29

**Comment by OyinOlamide** [comment]
OoOo312cb9516543fa90ddbd4b09c2a397c383b9850d62e4134bc5984195b8d409a80

**Comment by web3guy0** [comment]
OoOo3050ccfe668d67a766d9a7ea26288f1cfcfe76f83b69e88b147cd606535099533

**Comment by kaekei** [comment]
OoOo32137d13c25a3a00a42707b1c5b1984ff21d29966ee88273daec215b0f4aa5b52

**Comment by Greenkay** [comment]
OoOo3039438150125b606e7868d2ed15f8fa9011d06dfb1c0a30b50799243cf9a0f68

**Comment by Iqbalyaya112** [comment]
OoOo21b42d6ee9b67b346cd2392af43794a7ad15c7aee1a9a847da24a3f1d738a344a
