### ISSUE TITLE
owshen wallet stuck on loading 

### ISSUE THREAD

**Issue by Aries1000** [OwshenNetwork/owshen#97]
it keeps loading but nothing happens

**Comment by teresaenalisan** [comment]
the loading / processing events is already running for more than 12 hrs. I cant send dive because it keeps showing error - wallet keeps restarting from 0 dive then 5 dives. 
![Uploading image.png…]()

**Comment by kendrick3000** [comment]
I don't know how my wallet deducted of gas and my dive is still not sending
![Uploading 20240124_231412.jpg…]()
