### ISSUE TITLE
WL wallet not receiving dive test tokens

### ISSUE THREAD

**Issue by noblepeter2000** [OwshenNetwork/owshen#98]
my wallet is among the whitelisted and i'm yet to get any dive @The Deep Sea  OoOo3091f4b426130e89b9a3101afb0757824903125fce78bc4715f2f7d39cd8bb237

**Comment by Iqbalyaya112** [comment]
my wallet is among the whitelisted and i'm yet to get any dive @the Deep Sea OoOo21b42d6ee9b67b346cd2392af43794a7ad15c7aee1a9a847da24a3f1d738a344a

**Comment by muhammad0128** [comment]
OoOo31512a61d861392100ab27b3c2442e8a41d169cc975caa965c841d744ecdbd59f

**Comment by muhammad0128** [comment]
my wallet is among the whitelisted and i'm yet to get any dive @the Deep Sea
OoOo31512a61d861392100ab27b3c2442e8a41d169cc975caa965c841d744ecdbd59f

**Comment by hathanhtai** [comment]
OoOo2051049c65eb8c4aa053ba80e23b9fb370a2613a62a324d78055e369ecee2d479

my wallet is among the whitelisted and i'm yet to get any dive @the Deep Sea

**Comment by neko-sunny** [comment]
my wallet is among the whitelisted and i'm yet to get any dive @the Deep Sea
OoOo2060112dda6a8a327f7e6d4d4b3d4fb2a6bd0c34eb1e68ae9ead9fba3b2360bc7

**Comment by kendrick3000** [comment]
my wallet is among the whitelisted and i'm yet to get any dive @the Deep Sea
OoOo328b5e68718d829eece14048246605c69216efe59ed882c351a33e3af45627eea

**Comment by OZZY0128** [comment]
![IMG-20240126-WA0001](https://github.com/OwshenNetwork/owshen/assets/94685288/b53ad2e3-bfb3-4e78-b29c-d81aea94da5a)
I can't get through with my mnemonics. Error or some what?

**Comment by OZZY0128** [comment]
my wallet is among the whitelisted and i'm yet to get any dive @the Deep Sea
OoOo320fd81435519f3b3af2ef9b571bcb32538602de6483e30ebafaccac28e8e934d

**Comment by Julietsexy1** [comment]
@the please help, my wallet is whitelisted but no test token coming to it

It's been like this for the past 3 days, and today I have spent more than 4 hours waiting for test token
OoOo306642b3e904035f092270d2201da6c97373da7ad98b7ed9844084f533dcfdd21

**Comment by mymieday** [comment]
I didn't get get dive token in my wallet despite completing the first task and getting whitelisted. I can't finish the second task cos I need the Dive token. 
OoOo20a7ad37a3fb462c3bfb3fe4fb1ed102fb68fde075bb827eee06a51aec0db1f79

**Comment by craience28** [comment]
OoOo21f04f32e4d91622a1eb4ffae7a130cc15de982d053500d069b45cce76dfccc4b

MY WALLET JUST KEEPS ON LOADING AND DOESNT SHOW MY DIVE TOKENS
ive been waiting for hours

![Untitled](https://github.com/OwshenNetwork/owshen/assets/146409658/0998c887-ffb0-47f6-8d50-4e05a0373eee)

**Comment by Lordse7enth** [comment]
OoOo21edfe5212ffe2dd261b59098aaccf4556913f9f9778ec14f85e69267f8146a54

My wallet keeps loading since 3 days ago. I can't get my DIVE and unable to proceed
![IMG-20240127-WA0032](https://github.com/OwshenNetwork/owshen/assets/95983389/9334882a-8c78-4470-8894-650bc5e4189f)

**Comment by vinibacha** [comment]
I didn't get get dive token in my wallet despite completing the first task and getting whitelisted in the Bermuda Airdrop. I can't finish the second task cos I need the Dive token.

OoOo30f2ef6280ea376636ab1fa2d748d030ab9395bd28632dae36d4027ee42ebe0fa

**Comment by owonikokong** [comment]
I didn't get any dive token in my wallet despite completing the first task and getting whitelisted in the Bermuda Airdrop. I can't finish the second task cos I need the Dive token.   

OoOo30afcbd31b9a2bf0412d2a621f7f650f72176a7ebfd6344d6016ffdf1cae5ee1f

**Comment by Iamopiti** [comment]
I didn't get the dive token and my wallet is eligible for the testnet


OoOo30f3719996c52c2b2a43226c7c855e65108041499a89ab3ec0dc80a82060ea954

**Comment by Dannyfroshh** [comment]
I need dive token to complete the testnet

OoOo21f897f8992d04e54d0331cbb7f445bb58086b2b63f4956446a81809b3b9d8b8b

**Comment by Freshdannyyo** [comment]
Cant complete the testnet without token

OoOo21c310b9f4edcd43fa1e6f18453e35a067f0f01c8b63a2814d1aa5d36eb06e6ad

**Comment by derajpaul** [comment]
OoOo222093394a5fddc2df97df25785703251481e6522e2eee9bb219f5437c1b4a8da 

In Airdrop list but didnt receive tokens. How can I perform testnet Sir...

**Comment by Momosoree** [comment]
OoOo30ae76401402d47583a1f20c6256ed4e23ecb6c7796d8de1eb7b005f6e5f0fe43


I didn't get the dive token and my wallet is eligible.

**Comment by Peaceight** [comment]
OoOo32d8181d58dda714cb3b38c6796ceadebab0e9c84db3d9ab43675ae8bc3ebb649
I've been unable to connect my wallet, I have DIVE but my wallet is not connecting, I switch to SEPOLIA network. I had try different wallet provide not working.

**Comment by notsalvia** [comment]
OoOo22d0790fe0390328c1aaa54581f22f29151a6b1c4bb9fb721aad0a4e59d4f6e63

Need DIVE for testnet submission, my wallet is eligible

**Comment by zaadddadf** [comment]
I didn't get any dive tokens and my wallet is eligible for testnet
I need a dive token to complete the testnet
OoOo20d63983e32e856b506ad648c154a9b6ef2c10c47cd9519fa55e439eac82946cf

**Comment by Momosoree** [comment]
Hi, so what's being done about it? If I may ask.

**Comment by Napoleon-Jahmiu** [comment]
OoOo30f794db35ff3b37ea3408607d3519509ae96c3ee5aaec268ded005af0bb92e87

I need some $DIVE TOKEN to complete the tasks

**Comment by Ansel-Coder** [comment]
Hi, Pls need some $DIVE tokens

OoOo22224a8f156d71558a0073f58d8ad787064e634ffae5567dc83a8ccce417d5299
